// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var React = require("react");
var ReactTestingLibrary = require("../src/ReactTestingLibrary.js");

function ReactTestingLibraryTest$Dummy(Props) {
  return React.createElement("div", undefined, "Hello World");
}

var Dummy = {
  make: ReactTestingLibraryTest$Dummy
};

Jest.test("render", (function (param) {
        return Jest.Expect.toMatchSnapshot(Jest.Expect.expect(ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, React.createElement(ReactTestingLibraryTest$Dummy, {}))));
      }));

exports.Dummy = Dummy;
/*  Not a pure module */
