// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var React = require("@testing-library/react");

function render(baseElement, container, hydrate, wrapper, queries, element) {
  var options = {
    baseElement: Js_undefined.fromOption(baseElement),
    container: Js_undefined.fromOption(container),
    hydrate: Js_undefined.fromOption(hydrate),
    wrapper: Js_undefined.fromOption(wrapper),
    queries: Js_undefined.fromOption(queries)
  };
  return React.render(element, options);
}

exports.render = render;
/* @testing-library/react Not a pure module */
