// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var DomTestingLibrary = require("rescript-dom-testing-library/lib/js/src/DomTestingLibrary.js");
var React = require("@testing-library/react");

function render(baseElement, container, hydrate, wrapper, queries, element) {
  var options = {
    baseElement: Js_undefined.fromOption(baseElement),
    container: Js_undefined.fromOption(container),
    hydrate: Js_undefined.fromOption(hydrate),
    wrapper: Js_undefined.fromOption(wrapper),
    queries: Js_undefined.fromOption(queries)
  };
  return React.render(element, options);
}

function renderElement(baseElement, container, hydrate, wrapper, queries, element) {
  var options = {
    baseElement: Js_undefined.fromOption(baseElement),
    container: Js_undefined.fromOption(container),
    hydrate: Js_undefined.fromOption(hydrate),
    wrapper: Js_undefined.fromOption(wrapper),
    queries: Js_undefined.fromOption(queries)
  };
  return Js_dict.get(React.render(element, options), "container");
}

var makeByAltTextOptions = DomTestingLibrary.makeByAltTextOptions;

var getByAltText = DomTestingLibrary.getByAltText;

var findByAltText = DomTestingLibrary.findByAltText;

var getAllByAltText = DomTestingLibrary.getAllByAltText;

var queryAllByAltText = DomTestingLibrary.queryAllByAltText;

var findAllByAltText = DomTestingLibrary.findAllByAltText;

var makeByDisplayValueOptions = DomTestingLibrary.makeByDisplayValueOptions;

var getByDisplayValue = DomTestingLibrary.getByDisplayValue;

var findByDisplayValue = DomTestingLibrary.findByDisplayValue;

var getAllByDisplayValue = DomTestingLibrary.getAllByDisplayValue;

var queryAllByDisplayValue = DomTestingLibrary.queryAllByDisplayValue;

var findAllByDisplayValue = DomTestingLibrary.findAllByDisplayValue;

var makeByLabelTextOptions = DomTestingLibrary.makeByLabelTextOptions;

var getByLabelText = DomTestingLibrary.getByLabelText;

var findByLabelText = DomTestingLibrary.findByLabelText;

var makeByPlaceholderTextOptions = DomTestingLibrary.makeByPlaceholderTextOptions;

var getByPlaceholderText = DomTestingLibrary.getByPlaceholderText;

var findByPlaceholderText = DomTestingLibrary.findByPlaceholderText;

var getAllByPlaceholderText = DomTestingLibrary.getAllByPlaceholderText;

var queryAllByPlaceholderText = DomTestingLibrary.queryAllByPlaceholderText;

var findAllByPlaceholderText = DomTestingLibrary.findAllByPlaceholderText;

var makeByRoleOptions = DomTestingLibrary.makeByRoleOptions;

var makeByRoleOptionsWithRegex = DomTestingLibrary.makeByRoleOptionsWithRegex;

var makeByRoleOptionsWithFunction = DomTestingLibrary.makeByRoleOptionsWithFunction;

var getByRole = DomTestingLibrary.getByRole;

var findByRole = DomTestingLibrary.findByRole;

var getAllByRole = DomTestingLibrary.getAllByRole;

var queryAllByRole = DomTestingLibrary.queryAllByRole;

var findAllByRole = DomTestingLibrary.findAllByRole;

var makeByTestIdOptions = DomTestingLibrary.makeByTestIdOptions;

var getByTestId = DomTestingLibrary.getByTestId;

var findByTestId = DomTestingLibrary.findByTestId;

var getAllByTestId = DomTestingLibrary.getAllByTestId;

var queryAllByTestId = DomTestingLibrary.queryAllByTestId;

var findAllByTestId = DomTestingLibrary.findAllByTestId;

var makeByTextOptions = DomTestingLibrary.makeByTextOptions;

var getByText = DomTestingLibrary.getByText;

var findByText = DomTestingLibrary.findByText;

var getAllByText = DomTestingLibrary.getAllByText;

var queryAllByText = DomTestingLibrary.queryAllByText;

var findAllByText = DomTestingLibrary.findAllByText;

var makeByTitleOptions = DomTestingLibrary.makeByTitleOptions;

var getByTitle = DomTestingLibrary.getByTitle;

var findByTitle = DomTestingLibrary.findByTitle;

var getAllByTitle = DomTestingLibrary.getAllByTitle;

var queryAllByTitle = DomTestingLibrary.queryAllByTitle;

var findAllByTitle = DomTestingLibrary.findAllByTitle;

var prettyDOM = DomTestingLibrary.prettyDOM;

var debugScreen = DomTestingLibrary.debugScreen;

exports.makeByAltTextOptions = makeByAltTextOptions;
exports.getByAltText = getByAltText;
exports.findByAltText = findByAltText;
exports.getAllByAltText = getAllByAltText;
exports.queryAllByAltText = queryAllByAltText;
exports.findAllByAltText = findAllByAltText;
exports.makeByDisplayValueOptions = makeByDisplayValueOptions;
exports.getByDisplayValue = getByDisplayValue;
exports.findByDisplayValue = findByDisplayValue;
exports.getAllByDisplayValue = getAllByDisplayValue;
exports.queryAllByDisplayValue = queryAllByDisplayValue;
exports.findAllByDisplayValue = findAllByDisplayValue;
exports.makeByLabelTextOptions = makeByLabelTextOptions;
exports.getByLabelText = getByLabelText;
exports.findByLabelText = findByLabelText;
exports.makeByPlaceholderTextOptions = makeByPlaceholderTextOptions;
exports.getByPlaceholderText = getByPlaceholderText;
exports.findByPlaceholderText = findByPlaceholderText;
exports.getAllByPlaceholderText = getAllByPlaceholderText;
exports.queryAllByPlaceholderText = queryAllByPlaceholderText;
exports.findAllByPlaceholderText = findAllByPlaceholderText;
exports.makeByRoleOptions = makeByRoleOptions;
exports.makeByRoleOptionsWithRegex = makeByRoleOptionsWithRegex;
exports.makeByRoleOptionsWithFunction = makeByRoleOptionsWithFunction;
exports.getByRole = getByRole;
exports.findByRole = findByRole;
exports.getAllByRole = getAllByRole;
exports.queryAllByRole = queryAllByRole;
exports.findAllByRole = findAllByRole;
exports.makeByTestIdOptions = makeByTestIdOptions;
exports.getByTestId = getByTestId;
exports.findByTestId = findByTestId;
exports.getAllByTestId = getAllByTestId;
exports.queryAllByTestId = queryAllByTestId;
exports.findAllByTestId = findAllByTestId;
exports.makeByTextOptions = makeByTextOptions;
exports.getByText = getByText;
exports.findByText = findByText;
exports.getAllByText = getAllByText;
exports.queryAllByText = queryAllByText;
exports.findAllByText = findAllByText;
exports.makeByTitleOptions = makeByTitleOptions;
exports.getByTitle = getByTitle;
exports.findByTitle = findByTitle;
exports.getAllByTitle = getAllByTitle;
exports.queryAllByTitle = queryAllByTitle;
exports.findAllByTitle = findAllByTitle;
exports.prettyDOM = prettyDOM;
exports.debugScreen = debugScreen;
exports.render = render;
exports.renderElement = renderElement;
/* DomTestingLibrary Not a pure module */
